name: budgetin_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Utility
  path: ^1.9.0
  intl: ^0.20.2
  timeago: ^3.6.0   # âœ… TAMBAHAN (INI YANG KURANG)

  # UI
  image_picker: ^1.0.7
  fl_chart: ^0.66.0
  path_provider: ^2.1.2


  font_awesome_flutter: ^10.6.0
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.8

  # Local storage
  shared_preferences: ^2.3.2

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.1.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
